title: 覚えたことを復唱してみる。だって、忘れっぽいんですもの。
author: okusama27

# baseurl: 'kamekokamekame.net'

paginate: 5
paginate_path: "/page:num/"

markdown: kramdown
theme: "minima"

twitter_username: okusama27
github_username:  okusama27

keep_files: ['assets']

# https://jekyllrb.com/docs/posts/
# https://github.com/jekyll/minima
gems:
  - jekyll-feed
