title: 覚えたことを復唱してみる。だって、忘れっぽいんですもの。
author: okusama27

paginate: 1

markdown: kramdown
theme: "minima"
twitter_username: okusama27

keep_files: ['assets']

# https://jekyllrb.com/docs/posts/
# https://github.com/jekyll/minima
gems: [jekyll-feed, jekyll-paginate]
